[project]
name = "erase-canvas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "graphics-py>=5.0.1.post1",
    "streamlit>=1.43.2",
]
